import { createFileRoute, Link } from "@tanstack/react-router";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { createSeoHead } from "@/lib/seo";
import { pageBreadcrumbs } from "@/lib/breadcrumbs";
import { createBreadcrumbList, createPageGraph, schemaScripts } from "@/lib/structured-data";

const breadcrumbs = pageBreadcrumbs("Terms of Service", "/terms");

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => {
    const title = "Terms of Service | Homent Residential Cleaning";
    const description = "Read the terms that apply to Homent residential cleaning quotations, bookings and services in South Africa.";
    const path = "/terms";
    return { ...createSeoHead({ title, description, path }), scripts: schemaScripts(createPageGraph(path, title, description), createBreadcrumbList(breadcrumbs)) };
  },
});

const headingClass = "text-2xl font-semibold tracking-tight text-[#5A1425] md:text-3xl";
const paragraphClass = "mt-4 leading-7 text-[#695E59]";

function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FBF7EF] text-[#322B2A]">
      <Navbar />
      <main>
        <header className="border-b border-[#C9A45B]/25 bg-[#F7F0E3] px-6 pb-20 pt-32 md:pb-24 md:pt-40">
          <div className="mx-auto max-w-6xl">
            <Breadcrumbs items={breadcrumbs} className="mb-12 text-[#5F4B46]" />
            <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#9A742E]">Clear service expectations</p>
            <h1 className="mt-5 text-4xl font-semibold tracking-[-0.035em] text-[#5A1425] sm:text-5xl md:text-6xl">Terms of Service</h1>
            <p className="mt-6 max-w-3xl text-lg leading-8 text-[#695E59]">These terms apply when a customer requests a quotation, accepts a booking and receives residential cleaning services from Homent Residential Cleaning.</p>
            <p className="mt-4 text-sm font-medium text-[#5A1425]">Last updated: 13 August 2026</p>
          </div>
        </header>
        <article className="mx-auto max-w-4xl space-y-14 px-6 py-16 lg:py-24">
          <section><h2 className={headingClass}>Quotations and bookings</h2><p className={paragraphClass}>Quotations are based on the information supplied about the property, condition, requested work and relevant circumstances. A quotation may change if the actual condition, size, access requirements or scope differs materially. Homent will explain and obtain approval before performing chargeable work outside the accepted scope.</p><p className={paragraphClass}>A requested date or automated acknowledgement is not a confirmed booking. A booking is confirmed only when Homent expressly accepts it, communicates the applicable service and payment details, and any required booking payment has been received and verified.</p></section>
          <section><h2 className={headingClass}>Customer responsibilities</h2><p className={paragraphClass}>Customers must provide accurate property, scope, contact and access information; identify fragile, damaged or specialist surfaces; disclose relevant pets, allergies or product restrictions; identify off-limits areas; and promptly correct information that becomes inaccurate.</p><p className={paragraphClass}>Customers should secure cash, jewellery, important documents and unusually valuable or fragile items where reasonably possible.</p></section>
          <section><h2 className={headingClass}>Access and failed access</h2><p className={paragraphClass}>Customers must arrange safe, lawful and timely access.</p><p className={paragraphClass}>If Homent cannot gain access at the agreed time, we will make a reasonable attempt to contact the customer and allow a reasonable short waiting period. If access remains unavailable, the visit may be treated as a late cancellation. Staff will not bypass security or enter unlawfully.</p></section>
          <section><h2 className={headingClass}>Cancellations and rescheduling</h2><p className={paragraphClass}>Customers should give at least <strong>24 hours’ notice</strong> to cancel or reschedule a confirmed booking. With at least 24 hours’ notice, cancellation or rescheduling is free of a cancellation charge, subject to availability for a replacement date.</p><p className={paragraphClass}>For less than 24 hours’ notice, a no-show or failed access, the standard late-cancellation charge is <strong>50% of the booked service price</strong>, subject to applicable South African consumer-law requirements and the circumstances of the cancellation. Homent may reduce or waive a charge where appropriate, including where the reserved slot is successfully filled or other circumstances reasonably justify it.</p><p className={paragraphClass}>A booking deposit or recurring advance and a cancellation charge are separate concepts. An amount held is not automatically forfeited in every cancellation scenario.</p></section>
          <section><h2 className={headingClass}>Initial and once-off payments</h2><p className={paragraphClass}>A <strong>50% deposit</strong> is required to secure an initial or once-off cleaning booking. The remaining <strong>50% is due upon completion</strong> of the service. Where the price is known, Homent’s quotation or booking correspondence will show the actual rand amount payable to secure the booking and the remaining balance.</p><p className={paragraphClass}>At launch, Homent supports manual EFT as a standard payment method. Proof of payment is evidence that a payment was initiated but is not final confirmation that cleared funds have been received. A booking that requires a deposit is financially confirmed when the required amount has been verified as received.</p></section>
          <section><h2 className={headingClass}>Recurring service and billing</h2><p className={paragraphClass}>Recurring residential cleaning has no fixed-term lock-in. Customers may end or pause the recurring arrangement with at least <strong>14 days’ notice</strong>. Changes to an individual visit remain subject to the normal 24-hour cancellation/rescheduling policy.</p><p className={paragraphClass}>Standard recurring billing is per job. Homent maintains an advance equal to <strong>50% of one normal scheduled visit</strong> toward the next appointment. After each completed visit, the amount paid settles the outstanding portion of that visit and replenishes the advance for the next scheduled visit.</p><p className={paragraphClass}>Eligible recurring customers may request month-end billing after two successfully paid months of standard recurring service. Approval is not automatic and requires the account to be current and in good standing. Approved customers choose a billing date from the 25th through the 7th salary-cycle window. If a selected 29th, 30th or 31st does not exist in a shorter month, the payment is due on that month’s final calendar day.</p><p className={paragraphClass}>Month-end billing uses the actual completed services in the billing cycle, so four- and five-visit months may have different totals. The existing 50% one-visit advance remains as standing security and no additional transition payment is required when an approved customer moves to month-end billing.</p></section>
          <section><h2 className={headingClass}>Late and disputed payments</h2><p className={paragraphClass}>Homent does not currently apply a late-payment fee or interest. If an amount remains unpaid, Homent may send payment reminders and place future service on hold rather than allowing unpaid services to accumulate. An outstanding amount of R50 or less does not by itself place the next service on hold, although the amount remains payable.</p><p className={paragraphClass}>A genuine payment or invoice dispute applies only to the specifically disputed amount. Collection consequences for that amount pause while it is reviewed in good faith, while undisputed amounts remain payable. Homent aims to begin human review within 2 business days and to resolve the dispute within 5 business days where reasonably possible.</p></section>
          <section><h2 className={headingClass}>Refunds, overpayments and price changes</h2><p className={paragraphClass}>Homent initiates an approved refund within <strong>5 business days</strong>. Additional time taken by the customer’s bank or payment provider to reflect the refund is outside Homent’s direct control. If a customer overpays, the customer may choose either a refund of the excess or account credit for future Homent services.</p><p className={paragraphClass}>Recurring customers will receive at least <strong>30 calendar days’ written notice</strong> before a recurring price increase takes effect. The notice will state the current price, new price and effective date. Services performed before the effective date are not retrospectively repriced.</p></section>
          <section><h2 className={headingClass}>Additional work</h2><p className={paragraphClass}>Work outside the accepted quotation or confirmed scope will not be charged unless the customer first approves the additional work and associated price or schedule change.</p></section>
          <section><h2 className={headingClass}>Service expectations</h2><p className={paragraphClass}>Homent will provide the accepted cleaning service with reasonable care and skill. Results depend on factors including surface age and condition, existing staining or damage, safe access, available time and agreed scope. Homent may decline or stop work that is unsafe, unlawful, outside the agreed service, requires specialist treatment or risks damage.</p></section>
          <section><h2 className={headingClass}>Complaints and remediation</h2><p className={paragraphClass}>Customers should report service concerns as soon as reasonably possible, preferably within <strong>48 hours</strong> of the service, with enough information for Homent to investigate. Homent will acknowledge the concern and aims to provide a substantive response within <strong>5 business days</strong>.</p><p className={paragraphClass}>Where a cleaning-quality concern is substantiated, Homent may first offer a reasonable remedy, including returning to correct the affected work where appropriate.</p></section>
          <section><h2 className={headingClass}>Loss or damage</h2><p className={paragraphClass}>Suspected loss or damage should be reported as soon as it is discovered, preferably within <strong>48 hours</strong>, with photographs or other relevant information where available. Homent will investigate before determining cause, responsibility or an appropriate remedy. Nothing in these terms excludes or limits rights or remedies that cannot lawfully be excluded under South African law.</p></section>
          <section><h2 className={headingClass}>Privacy and communications</h2><p className={paragraphClass}>Homent handles personal information for enquiries, quotations, bookings and service delivery as explained in our <Link to="/privacy" className="font-semibold text-[#5A1425] underline underline-offset-4">Privacy Policy</Link>.</p></section>
          <section><h2 className={headingClass}>Governing law and contact</h2><p className={paragraphClass}>These terms and Homent’s services are governed by the laws of the Republic of South Africa. Nothing in these terms removes statutory consumer rights that apply to a customer.</p><p className={paragraphClass}>General enquiries and POPIA requests may be sent to <a className="font-semibold text-[#5A1425] underline underline-offset-4" href="mailto:info@homent.co.za">info@homent.co.za</a>.</p></section>
        </article>
      </main>
      <Footer />
    </div>
  );
}
